services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "${DB_PORT:-1433}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-SqlServer2024!}
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      app-network:
        ipv4_address: 172.16.5.30

volumes:
  sqlserver-data:

networks:
  app-network:
    external: true
    name: app-network
